EDINET_API_BASE_URL = "https://api.edinet-fsa.go.jp/api/v2"
EDINET_SEARCH_EMPTY_TTL_DAYS = 1
EDINET_SEARCH_HIT_TTL_DAYS = 30
EDINET_SEARCH_PAST_TTL_DAYS = 3650
EDINET_DOCUMENT_INDEX_VERSION = "edinet-doc-index-v1"
EDINET_DOCUMENT_INDEX_BATCH_SIZE = 2
EDINET_DOCUMENT_INDEX_MIN_RANGE_DAYS = 30
EDINET_DOCUMENT_INDEX_KEEP_YEARS = 6
EDINET_FILINGS_DEFAULT_YEARS = 3
EDINET_WARMUP_DEFAULT_YEARS = 3
EDINET_XBRL_MAX_BYTES = 2 * 1024 ** 3  # 2 GB
EDINET_CACHE_LOCK_POLL_SECONDS = 0.2
EDINET_CACHE_LOCK_NOTICE_SECONDS = 1.0
EDINET_CACHE_LOCK_STALE_SECONDS = 10 * 60
EDINET_CACHE_LOCK_TIMEOUT_SECONDS = 3 * 60

# 財務省 JGB 利回り CSV
MOF_JGB_ALL_CSV_URL     = "https://www.mof.go.jp/jgbs/reference/interest_rate/data/jgbcm_all.csv"
MOF_JGB_CURRENT_CSV_URL = "https://www.mof.go.jp/jgbs/reference/interest_rate/jgbcm.csv"
